spring:
  application:
    name: "my-microservice"

  profiles:
    active: "dev"

server:
  port : 8081

---

spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: gourav
    password: Indoqubix#55
  batch:
    job:
      enabled: false

    initialize-schema: always



